spring:
  datasource:
    url: jdbc:h2:file:./tree;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  datasource:
#    url: jdbc:mysql://localhost:3306/kotlin_restapi_db
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true