http://localhost:8080/tree/1

###

http://localhost:8080/tree

###

POST http://localhost:8080/tree/add
Content-Type: application/json

{
  "userId": 1,
  "parentId": 10,
  "title": "test",
  "description": "testDescription",
  "importance": 1,
  "progress": 0.0
}

###

DELETE http://localhost:8080/tree/delete/3

###

POST http://localhost:8888/tree/add
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzZWN1cmUtYXBpIiwiYXVkIjoic2VjdXJlLWFwcCIsInN1YiI6ImZvbyIsImV4cCI6MTU4Mzg1NjYwMCwicm9sIjpbIlJPTEVfVVNFUiJdfQ.qwMCjzxST6N6dBHK9X_lgRv1Fesz1dP8yk0q1yXnbAw3CMxoxLmz2QQpdyoyZvSjPDHrZqN4QdhEKz8Q5N6evw

{
  "id": 33,
  "userId": 2,
  "parentId": 3,
  "title": "testUpdateTitle",
  "description": "testUpdateDescription",
  "importance": 100,
  "progress": 100.0
}

###

POST http://localhost:8888/tree/update
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzZWN1cmUtYXBpIiwiYXVkIjoic2VjdXJlLWFwcCIsInN1YiI6ImZvbyIsImV4cCI6MTU4Mzg1NjYwMCwicm9sIjpbIlJPTEVfVVNFUiJdfQ.qwMCjzxST6N6dBHK9X_lgRv1Fesz1dP8yk0q1yXnbAw3CMxoxLmz2QQpdyoyZvSjPDHrZqN4QdhEKz8Q5N6evw

{
  "id": 22,
  "userId": 2,
  "parentId": 3,
  "title": "testUpdateTitle",
  "description": "testUpdateDescription",
  "importance": 100,
  "progress": 100.0
}

###
GET http://localhost:8888/login

###
POST http://localhost:8888/api/authenticate
Content-Type: application/json

{
"username": "foo",
"password": "foo"
}

###
POST http://localhost:8888/api/authenticate?username=user&password=password

###
GET http://localhost:8888/tree
Authorization: Bearer Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzZWN1cmUtYXBpIiwiYXVkIjoic2VjdXJlLWFwcCIsInN1YiI6InVzZXIiLCJleHAiOjE1ODI5MDkzMTUsInJvbCI6WyJST0xFX1VTRVIiXX0.RE4veDQJKMv-2wrX4Pf2U2k3u5BtYohz1ubDb-8PHHMIP24yCOcnlfu40PA7xYX8RT_SA-zjknJX74WDMGqJhg

###
GET http://localhost:8888/tree

###
